spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_agent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 5000
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    database: 0
  application:
    name: yoyo_common

jwt:
  secret: Cel1fqtXo0lLw6IuwFWaDC0xKEg3p+X16qDFNg+anVY=
  expiration: 7200000
  token-expire: 7200

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.entity